version: '3'

services:
  reiverr:
    image: ghcr.io/aleksilassila/reiverr:latest
    container_name: reiverr
    ports:
      - ${APP_PORT}:9494
    environment:
      - SECRET=your_secret_here # optional, used to sign JWT tokens for authentication. If not set, sessions will not persist between server restarts. Use a random string.
      - ADMIN_USERNAME=admin # optional
      - ADMIN_PASSWORD=admin # optional
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.maintainerr-web-redirect.redirectscheme.scheme: https
      traefik.http.services.maintainerr.loadbalancer.server.port: 9494
      # Web
      traefik.http.routers.maintainerr-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.maintainerr-insecure.entrypoints: web
      traefik.http.routers.maintainerr-insecure.service: maintainerr
      traefik.http.routers.maintainerr-insecure.middlewares: maintainerr-web-redirect
      # Websecure
      traefik.http.routers.maintainerr.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.maintainerr.entrypoints: websecure
      traefik.http.routers.maintainerr.service: maintainerr
      traefik.http.routers.maintainerr.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.maintainerr-local-insecure.rule: Host(`maintainerr.${LOCAL_DOMAIN}`)
      traefik.http.routers.maintainerr-local-insecure.entrypoints: web
      traefik.http.routers.maintainerr-local-insecure.service: maintainerr
      traefik.http.routers.maintainerr-local-insecure.middlewares: maintainerr-web-redirect
      # Local domain secure
      traefik.http.routers.maintainerr-local.rule: Host(`maintainerr.${LOCAL_DOMAIN}`)
      traefik.http.routers.maintainerr-local.entrypoints: websecure
      traefik.http.routers.maintainerr-local.service: maintainerr
      traefik.http.routers.maintainerr-local.tls: true
      runtipi.managed: true
